export const NFT_NAME_MAP = new Map<string, string>([
  ["frogana", "froganas"],
  ["chads-1", "chadswtf"],
  ["mad-lads", "mad_lads"],
  ["famous-fox-federation-1", "famous_fox_federation"],
  ["retardio-cousins", "retardio_cousins"],
  ["smb-gen2", "solana_monkey_business"],
  ["urban-node", "urbannode"],
  ["claynosaurz-1", "claynosaurz"],
  ["p9-nodes-collection", "p9_nodes"],
  ["blood-io", "blood_solutions"],
  ["sharx-by-sharky-fi", "sharx"],
  ["degods-2", "degods"],
  ["ggsg", "galactic_geckos"],
  ["bando-kids", "bando"],
  ["transdimensional-fox-federation-1", "transdimensional_fox_federation"],
  ["lifinity-flares", "lifinity_flares"],
  ["degen-fat-cats", "degenfatcats"],
  ["flash-trade-1", "flashtrade"],
  ["traptardio", "traptardio_"],
  ["stylish-studs", "stylish_studs"],
  ["kanpai-pandas-2", "kanpaipandas"],
  ["play-solana-nft", "play_solana"],
  ["the-backwoods-1", "backwoods"],
]);
